### PR TITLE
WIP: Some bulk changes I made to support locally stored wheels

### PR DESCRIPTION
**Pull request by joshclimacell**
I made it so that PyPI packages without available wheels get downloaded/built and stored to a local dir, and so that the generated `.bzl` file automatically references them appropriately (using `filegroup` instead of `http_file`). (A lot of this was already in the existing code, so I was mostly just tweaking things so that everything gets generated in a way I liked...) I removed the `wheelURLPrefix` flag...

It's not at all clear that this is a generically useful change, but thought I'd run it by the original author to see if anything is worth incorporating into the main repo. If it does seem generically useful, probably still requires more documentation/clean up/etc. at a minimum before appropriate for merging.

Other miscellaneous things:
* Changes to support Python 3 compatibility
* Some renames that helped me understand the code a bit better
* Expose `PyZProvider` so that it can be imported, to allow extending `rules_pyz` functionality

Also. This repo is awesome. Fantastic work. So glad that you made this publicly available since I think it could be really helpful -- currently investigating using it quite broadly.

### CODE REVIEW

**Comment by joshclimacell** [comment]
@evanj

**Comment by joshclimacell** [comment]
Also, here is my wrapper script for my repo that calls `pip_generate` to generate the PyPI dependency rules, in case it helps clarify what I was going for:

```bash
#!/bin/bash
#
# Usage (from base dir of repo):
#   third_party/pypi/update_rules.sh

BASE_DIR="third_party/pypi"
WHEELS_DIR_NAME="wheels"
RULES_FILE_NAME="rules.bzl"

function update() {
    reqs_file="$1"
    output_dir="$2"
    python_path="$3"

    bazel build @rules_pyz//pypi:pip_generate_wrapper && \
    bazel-bin/external/rules_pyz/pypi/pip_generate_wrapper \
        -requirements "$BASE_DIR/${reqs_file}" \
        -outputDir "$BASE_DIR/$output_dir" \
        -wheelDir "$WHEELS_DIR_NAME" \
        -outputBzlFileName "$RULES_FILE_NAME" \
        -pythonPath "$python_path" \
        -workspacePrefix "${output_dir}_"
}

if [[ ! -e "$BASE_DIR/py2_requirements.txt" ]]; then
    echo "Must be run from repo root"
    exit 1
fi

update py2_requirements.txt py2 python2
update py3_requirements.txt py3 python3
```

**Comment by evanj** [comment]
Woah this is super exciting! I can't believe anyone else is actually looking at this. I hope its been useful!

I am definitely willing to these accept changes, particularly if it works for you. Be warned: I'm not using Python3 at the moment, so it is highly likely I'll break this accidentally in the future :)

If you fix the conflicts is `simplepack.go` and remove the compiled files in `tools`, I'll merge it and re-generate the binaries?

Additionally: I currently have an experimental change to flip the default mode in this repository from "zip everything" to "build a directory tree of symlinks, which can be *optionally* zipped". It seems faster to build and takes up less disk space.

**Comment by evanj** [comment]
Now that I think about it: if you are actually using this, maybe it is time to set up CircleCI or similar for this repository, so we could have tests that these changes in fact still work :)

**Comment by joshclimacell** [comment]
Thanks @evanj! I did as you suggested...

The symlink thing sounds interesting...

Yeah, setting up some automatic testing would be amazing! Not quite ready to volunteer to do this myself though. :)

**Comment by joshclimacell** [comment]
Things I still need to do before appropriate for merging:

- Update documentation
- Ensure all tests run

**Comment by joshclimacell** [comment]
#2

**Comment by joshclimacell** [comment]
Gentle ping @evanj -- thoughts on this?

**Comment by evanj** [comment]
Whoops sorry I was on vacation. This seems good to me, I'm going to merge it. Thanks!

**Comment by joshclimacell** [comment]
Whoops, sorry about that. I made a similar cross-compatibility fix here: https://github.com/climacell/rules_pyz/commit/4132acf316bf7f37b093aef76abdfa909f8314fa

**Pull request merged**
